---
- name: OpenVPN | Install | Set Distro/Version specific variables
  include_vars: "{{ item }}"
  tags: ['common','packages','pki','openvpn','dns','harden','sysctl','umask','services','kernel','misc','auditd','firewall','password','users','sshd','aide']
  with_first_found:
    #- "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    #- "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    #- "../vars/default.yml"
  notify:
    - clear history

- include: packages.yml
  tags: ['packages']

- include: pki.yml
  tags: ['pki','creds']

- include: openvpn.yml
  tags: ['openvpn']

- include: dns.yml
  tags: ['dns']

- include: harden_sysctl.yml
  when: ansible_virtualization_type != "docker"
  tags: ['sysctl', 'harden']

- include: harden_umask.yml
  tags: ['umask', 'harden']

- include: harden_services.yml
  tags: ['services', 'harden']

- include: harden_kernel.yml
  when: ansible_virtualization_type != "docker"
  tags: ['kernel', 'harden']

- include: harden_misc.yml
  tags: ['misc', 'harden']

- include: harden_auditd.yml
  tags: ['auditd', 'harden']

- include: firewall.yml
  tags: ['firewall', 'harden']

- include: harden_password.yml
  tags: ['password', 'harden']

- include: harden_users.yml
  tags: ['users', 'harden']

- include: harden_sshd.yml
  tags: ['sshd', 'harden']

- include: harden_aide.yml
  tags: ['aide', 'harden']
