---
- name: Setting harden value
  set_fact:
    cacheable: true
    harden: "{{ harden | default(false) }}"

- name: OpenVPN | Install | Set Distro/Version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    #- "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    #- "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    #- "../vars/default.yml"
  notify:
    - clear history

- include: packages.yml
- include: pki.yml
- include: openvpn.yml
- include: dns.yml
- include: harden_sysctl.yml
  when: ansible_virtualization_type != "docker" and harden
- include: harden_umask.yml
  when: harden
- include: harden_services.yml
  when: harden
- include: harden_kernel.yml
  when: ansible_virtualization_type != "docker" and harden
- include: harden_misc.yml
  when: harden
- include: harden_auditd.yml
  when: harden

- include: firewall.yml
  when: harden
- include: harden_password.yml
  when: harden
- include: harden_users.yml
  when: harden
- include: harden_sshd.yml
  when: harden
- include: harden_aide.yml
  when: harden
