- name: Add clients to OpenVPN's PKI
# ========================================================
  # Allows caller to override hosts using '-e cmd_hosts='
  hosts: "{{ cmd_hosts | default('openvpn_vpn') }}"

  roles:
    - add_clients
